test_pdb.py: Introduce MyBytesIO class
Its `write` method can take bytes or Unicode data.

This solves the following exception in Python 3:
    TypeError: 'str' does not support the buffer interface