fix(ci): Travis: pypy3: use pypy3.6-7.3.3
With 7.3.1:

> testing/test_pdb.py:3479::test_hidden_pytest_frames_f_local_nondict -
> AssertionError: assert [] == [('__return__', None)]
>  Right contains one more item: ('__return__', None)

Job: https://travis-ci.com/github/pdbpp/pdbpp/jobs/495704224#L572

In worked with 7.1.1 before, so this appears to be an intermediate
regression in pypy3 itself.